# conf/layer.conf
# Copyright (C) 2026 Oleh Kravchenko <oleg@kaa.org.ua>
# Released under the MIT license (see LICENSE for the terms)

# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
        ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "kaa"
BBFILE_PATTERN_kaa = "^${LAYERDIR}/"
BBFILE_PRIORITY_kaa = "6"

LAYERDEPENDS_kaa = "core"
LAYERSERIES_COMPAT_kaa = "scarthgap"
